#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 检查提交信息格式
commit_regex='^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?: .{1,50}'
error_msg="提交失败：提交信息格式不符合要求。应该使用格式：type(scope): subject，例如：feat(login): add login form component"

if ! grep -iqE "$commit_regex" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi 